/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Delete;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asad Yousuf
 */
public class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Updatestudent = new javax.swing.JButton();
        Deleteteacher = new javax.swing.JButton();
        Deletestudent = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Addnewteaacher = new javax.swing.JButton();
        Addstudent = new javax.swing.JButton();
        viewteacher = new javax.swing.JButton();
        Viewstudent = new javax.swing.JButton();
        Updateteacher = new javax.swing.JButton();
        Deletcourse = new javax.swing.JButton();
        Addcourse1 = new javax.swing.JButton();
        Deletcourse1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Updatestudent.setBackground(new java.awt.Color(153, 153, 153));
        Updatestudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Updatestudent.setText("Update Student");
        Updatestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatestudentActionPerformed(evt);
            }
        });

        Deleteteacher.setBackground(new java.awt.Color(153, 153, 153));
        Deleteteacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deleteteacher.setText("Delete Teacher");
        Deleteteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteteacherActionPerformed(evt);
            }
        });

        Deletestudent.setBackground(new java.awt.Color(153, 153, 153));
        Deletestudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletestudent.setText("Delete Student");
        Deletestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletestudentActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "ADMINISTRATOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Addnewteaacher.setBackground(new java.awt.Color(153, 153, 153));
        Addnewteaacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addnewteaacher.setText("Add New Teacher");
        Addnewteaacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddnewteaacherActionPerformed(evt);
            }
        });

        Addstudent.setBackground(new java.awt.Color(153, 153, 153));
        Addstudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addstudent.setText("Add Student");
        Addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstudentActionPerformed(evt);
            }
        });

        viewteacher.setBackground(new java.awt.Color(153, 153, 153));
        viewteacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewteacher.setText("View Teacher");
        viewteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewteacherActionPerformed(evt);
            }
        });

        Viewstudent.setBackground(new java.awt.Color(153, 153, 153));
        Viewstudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Viewstudent.setText("View Student");
        Viewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewstudentActionPerformed(evt);
            }
        });

        Updateteacher.setBackground(new java.awt.Color(153, 153, 153));
        Updateteacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Updateteacher.setText("Update Teacher");
        Updateteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateteacherActionPerformed(evt);
            }
        });

        Deletcourse.setBackground(new java.awt.Color(153, 153, 153));
        Deletcourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletcourse.setText("Delete Course");
        Deletcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletcourseActionPerformed(evt);
            }
        });

        Addcourse1.setBackground(new java.awt.Color(153, 153, 153));
        Addcourse1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addcourse1.setText("Add Course");
        Addcourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addcourse1ActionPerformed(evt);
            }
        });

        Deletcourse1.setBackground(new java.awt.Color(153, 153, 153));
        Deletcourse1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletcourse1.setText("Log Out");
        Deletcourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deletcourse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Deleteteacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Updateteacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Addnewteaacher, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(viewteacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Addcourse1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Addstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Viewstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Updatestudent, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(Deletestudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Deletcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(Deletcourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addnewteaacher, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewteacher, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Viewstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updatestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updateteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Deleteteacher, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(Deletestudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addcourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Deletcourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatestudentActionPerformed
        Updatestudent a= new Updatestudent();
        a.setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_UpdatestudentActionPerformed

    private void DeleteteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteteacherActionPerformed
        Deleteteacher a= new  Deleteteacher();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_DeleteteacherActionPerformed

    private void DeletestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletestudentActionPerformed
        Deletestudent a= new  Deletestudent();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_DeletestudentActionPerformed

    private void AddnewteaacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddnewteaacherActionPerformed
        Insertteacher  a= new Insertteacher();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_AddnewteaacherActionPerformed

    private void AddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstudentActionPerformed
        InsertStudent  a= new InsertStudent();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_AddstudentActionPerformed

    private void viewteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewteacherActionPerformed
        Viewteacherrecord a= new Viewteacherrecord();
        a.setVisible(true);
        this.dispose();;
        // TODO add your handling code here:
    }//GEN-LAST:event_viewteacherActionPerformed

    private void ViewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewstudentActionPerformed
        Viewstudentrecord a= new Viewstudentrecord();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ViewstudentActionPerformed

    private void UpdateteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateteacherActionPerformed
        Updateteacher1 a= new Updateteacher1();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_UpdateteacherActionPerformed

    private void DeletcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletcourseActionPerformed
        
        try {
            Delete_Course b;
            b = new Delete_Course();
            b.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_DeletcourseActionPerformed

    private void Addcourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addcourse1ActionPerformed
Add_course a=new Add_course();
a.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Addcourse1ActionPerformed

    private void Deletcourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deletcourse1ActionPerformed
Login b=new Login();
b.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Deletcourse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addcourse1;
    private javax.swing.JButton Addnewteaacher;
    private javax.swing.JButton Addstudent;
    private javax.swing.JButton Deletcourse;
    private javax.swing.JButton Deletcourse1;
    private javax.swing.JButton Deletestudent;
    private javax.swing.JButton Deleteteacher;
    private javax.swing.JButton Updatestudent;
    private javax.swing.JButton Updateteacher;
    private javax.swing.JButton Viewstudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewteacher;
    // End of variables declaration//GEN-END:variables
}
